package com.hiway.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoom<M extends BaseRoom<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setNo(java.lang.String no) {
		set("NO", no);
	}

	public java.lang.String getNo() {
		return get("NO");
	}

	public void setCapacity(java.lang.String capacity) {
		set("CAPACITY", capacity);
	}

	public java.lang.String getCapacity() {
		return get("CAPACITY");
	}

	public void setProjector(java.lang.String projector) {
		set("PROJECTOR", projector);
	}

	public java.lang.String getProjector() {
		return get("PROJECTOR");
	}

	public void setKeyboard(java.lang.String keyboard) {
		set("KEYBOARD", keyboard);
	}

	public java.lang.String getKeyboard() {
		return get("KEYBOARD");
	}

	public void setWifi(java.lang.String wifi) {
		set("WIFI", wifi);
	}

	public java.lang.String getWifi() {
		return get("WIFI");
	}

}
