package com.hiway.model;

import com.hiway.model.BaseRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Room extends BaseRoom<Room> {
	public static final Room dao = new Room();
}
